// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Xlab_Task.Models
{
    public partial class sp_GetInvoiceByIDResult
    {
        public int Invoice_ID { get; set; }
        public int Product_ID { get; set; }
        public double? Product_Price { get; set; }
        public int? Product_Quantity { get; set; }
        public double? TotalPrice { get; set; }
        public string Client_Name { get; set; }
        public DateTime? Invoice_Date { get; set; }
    }
}
