// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Xlab_Task.Models
{
    public partial class sp_GetInvoiceTotalsResult
    {
        public int? Invoice_Total_Items { get; set; }
        public double? Invoice_TotalPrice { get; set; }
    }
}
