// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Xlab_Task.Models;

namespace Xlab_Task.Data
{
    public partial interface ISalesDbContextProcedures
    {
        Task<int> sp_CreateAnewInvoiceAsync(string Client_Name, DateTime? Invoice_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_deleteInvoiceAsync(int? Invoice_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetInvoiceByIDResult>> sp_GetInvoiceByIDAsync(int? Invoice_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetInvoiceTotalsResult>> sp_GetInvoiceTotalsAsync(int? Invoice_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertItemsIntoInvoiceAsync(int? Invoice_ID, int? Product_Id, double? Product_Price, int? Product_Quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_UpdateInvoiceAsync(int? Invoice_ID, string Client_Name, DateTime? Invoice_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_UpdateInvoiceItemsAsync(int? Invoice_ID, int? Product_ID, double? Product_Price, int? Product_Quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
